# since the repository is private I will keep the authentication info here,
# although it is not the best practice.
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=2805
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#for now create-drop is just for testing
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

application.security.jwt.secret-key=5712e6163faa50d7862b346e9763476aa08f1323369fc207dde807412581208a

# coding exercises
judge0.api.key=2855538cc1mshe74fe3a79ef58e4p187108jsnb229fc724e84
spring.sql.init.platform=postgres
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true