# since the repository is private I will keep the authentication info here,
# although it is not the best practice.
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.config.import=optional:file:.env[.properties]

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#for now create-drop is just for testing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

application.security.jwt.secret-key=${JWT_SECRET_KEY}

# admin account
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# coding exercises
judge0.api.key=${JUDGE0_API_KEY}
spring.sql.init.platform=postgres
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true