# since the repository is private I will keep the authentication info here,
# although it is not the best practice.
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/platformDB
spring.datasource.username=postgres
spring.datasource.password=2805
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#for now create-drop is just for testing
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

application.security.jwt.secret-key=5712e6163faa50d7862b346e9763476aa08f1323369fc207dde807412581208a